# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8faed8a247dfef81c1fea1c2c746977669ece35d04f4172134353a1f471e920976040b954d405c365336eae9116c916f9da9a1d096d046338766abe4dd638f6c

test:
  secret_key_base: e2160c068f9282f6771b70a32b5c327f4f63fe7f55045d4839a60279006da60a1fd4f30a835158ff961f0dedc51488da8eb0b6b8e7577771cc3cf5f30e33c365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
